apiVersion: apps/v1
kind: Deployment
metadata:
  name: anil-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anil-app
  template:
    metadata:
      labels:
        app: anil-app
    spec:
      containers:
      - name: anil-container
        image: nginx
        ports:
        - containerPort: 80
